/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteUno;

/**
 *
 * @author user01
 */
public class VentanaDos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaDos
     */
    public VentanaDos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpanelUno = new javax.swing.JPanel();
        jPanelDos = new javax.swing.JPanel();
        btnRelacionAudioImagen = new javax.swing.JButton();
        btnRelacionImagenAudio = new javax.swing.JButton();
        jPanelMenu = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanelUno.setPreferredSize(new java.awt.Dimension(600, 300));
        jpanelUno.setLayout(new java.awt.GridBagLayout());

        jPanelDos.setPreferredSize(new java.awt.Dimension(600, 225));
        jPanelDos.setLayout(new java.awt.GridLayout(2, 0));

        btnRelacionAudioImagen.setText("Relacion audio - imagen");
        btnRelacionAudioImagen.setAlignmentY(0.0F);
        btnRelacionAudioImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelacionAudioImagenActionPerformed(evt);
            }
        });
        jPanelDos.add(btnRelacionAudioImagen);

        btnRelacionImagenAudio.setText("Relacion imagen - audio");
        btnRelacionImagenAudio.setAlignmentY(0.0F);
        btnRelacionImagenAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelacionImagenAudioActionPerformed(evt);
            }
        });
        jPanelDos.add(btnRelacionImagenAudio);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        jpanelUno.add(jPanelDos, gridBagConstraints);

        jPanelMenu.setMinimumSize(new java.awt.Dimension(600, 75));
        jPanelMenu.setLayout(new java.awt.BorderLayout());

        btnRegresar.setText("jButton3");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanelMenu.add(btnRegresar, java.awt.BorderLayout.WEST);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jpanelUno.add(jPanelMenu, gridBagConstraints);

        getContentPane().add(jpanelUno, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRelacionAudioImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelacionAudioImagenActionPerformed
        VentanaAudioImagenBeta ventana = new VentanaAudioImagenBeta();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRelacionAudioImagenActionPerformed

    private void btnRelacionImagenAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelacionImagenAudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelacionImagenAudioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRelacionAudioImagen;
    private javax.swing.JButton btnRelacionImagenAudio;
    private javax.swing.JPanel jPanelDos;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jpanelUno;
    // End of variables declaration//GEN-END:variables
}
